redis_requests_queue:
  host:                           "localhost"
  port:                           "1640"
  username:                       "default"
  password:                       ""
  queue_name:                     "deposit_requests_queue"
  timeout:                        5 # s

redis_responses_queue:
  host:                           "localhost"
  port:                           "1640"
  username:                       "default"
  password:                       ""
  queue_name:                     "deposit_responses_queue"
  timeout:                        5 # s

postgresql_wallet_database:
  host:                           "localhost"
  port:                           "5432"
  username:                       "postgres"
  password:                       "postgres"
  database:                       "postgres"
  balance_table:                  "postgres.wallet.balances"
  transactions_table:             "postgres.wallet.transactions"
