redis_requests_queue:
  host:                           "localhost"
  port:                           "1640"
  username:                       "default"
  password:                       ""
  queue_name:                     "balance_requests_queue"
  timeout:                        5 # s

redis_responses_queue:
  host:                           "localhost"
  port:                           "1640"
  username:                       "default"
  password:                       ""
  queue_name:                     "balance_responses_queue"
  timeout:                        5 # s